In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

### Reading the data file in df

**Read the csv data file and disply its head**

In [4]:
# Code here please

df = pd.read_csv("mammographic_masses_data_clean.csv")

In [7]:
df.head()

   BI-RADS  Age  Shape  Margin  Density  Target
0        5   67      3       5        3       1
1        5   58      4       5        3       1
2        4   28      1       1        3       0
3        5   57      1       5        3       1
4        5   76      1       4        3       1

   BI-RADS  Age  Shape  Margin  Density  Target
0        5   67      3       5        3       1
1        5   58      4       5        3       1
2        4   28      1       1        3       0
3        5   57      1       5        3       1
4        5   76      1       4        3       1

**How many data entries you have?**

In [8]:
# Code here please

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 830 entries, 0 to 829
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   BI-RADS  830 non-null    int64
 1   Age      830 non-null    int64
 2   Shape    830 non-null    int64
 3   Margin   830 non-null    int64
 4   Density  830 non-null    int64
 5   Target   830 non-null    int64
dtypes: int64(6)
memory usage: 39.0 KB

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 830 entries, 0 to 829
Data columns (total 6 columns):
BI-RADS    830 non-null int64
Age        830 non-null int64
Shape      830 non-null int64
Margin     830 non-null int64
Density    830 non-null int64
Target     830 non-null int64
dtypes: int64(6)
memory usage: 39.0 KB

**Which type of cancer is common?**

In [9]:
# Code here please

df['Target'].value_counts()

Target
0    427
1    403
Name: count, dtype: int64

0    427
1    403
Name: Target, dtype: int64

**Reproduce the output to show some statistics**

In [10]:
# Code here please


df.describe()

          BI-RADS         Age       Shape      Margin     Density      Target
count  830.000000  830.000000  830.000000  830.000000  830.000000  830.000000
mean     4.393976   55.781928    2.781928    2.813253    2.915663    0.485542
std      1.888371   14.671782    1.242361    1.567175    0.350936    0.500092
min      0.000000   18.000000    1.000000    1.000000    1.000000    0.000000
25%      4.000000   46.000000    2.000000    1.000000    3.000000    0.000000
50%      4.000000   57.000000    3.000000    3.000000    3.000000    0.000000
75%      5.000000   66.000000    4.000000    4.000000    3.000000    1.000000
max     55.000000   96.000000    4.000000    5.000000    4.000000    1.000000

          BI-RADS         Age       Shape      Margin     Density      Target
count  830.000000  830.000000  830.000000  830.000000  830.000000  830.000000
mean     4.393976   55.781928    2.781928    2.813253    2.915663    0.485542
std      1.888371   14.671782    1.242361    1.567175    0.350936    0.500092
min      0.000000   18.000000    1.000000    1.000000    1.000000    0.000000
25%      4.000000   46.000000    2.000000    1.000000    3.000000    0.000000
50%      4.000000   57.000000    3.000000    3.000000    3.000000    0.000000
75%      5.000000   66.000000    4.000000    4.000000    3.000000    1.000000
max     55.000000   96.000000    4.000000    5.000000    4.000000    1.000000

** Do the Train Test Split** using test size 0.3

In [16]:
# Features and target

X = df.drop('Target', axis=1)
y = df['Target']

In [13]:
# Train-Test Split (30% test data)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [14]:
# Check shapes

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (581, 5)
X_test shape: (249, 5)
y_train shape: (581,)
y_test shape: (249,)

### Decision Tree
**Importing decision tree classifier and create its instance**

In [32]:
from sklearn.tree import DecisionTreeClassifier

# Create Decision Tree model instance
dt_model = DecisionTreeClassifier(random_state=42)

**Fit the training data to the model**

In [33]:
dt_model = DecisionTreeClassifier()
dt_model.fit(X_train, y_train)

DecisionTreeClassifier()

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

**What is the Score of the model?**

In [29]:
score = dt_model.score(X_test, y_test)
print("Model Accuracy:", score)

Model Accuracy: 0.7590361445783133

The Decision Tree classifier achieved an accuracy of 75.10% on the test dataset.

In [30]:
from sklearn.metrics import confusion_matrix, classification_report

y_pred = dt_model.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[99 28]
 [32 90]]
              precision    recall  f1-score   support

           0       0.76      0.78      0.77       127
           1       0.76      0.74      0.75       122

    accuracy                           0.76       249
   macro avg       0.76      0.76      0.76       249
weighted avg       0.76      0.76      0.76       249